title: "Mingze Li"
name: "Mingze Li"
description: "Mingze Li — research portfolio and publications"

remote_theme: "mmistakes/minimal-mistakes"

url: "https://mingze101.github.io"
baseurl: ""
locale: "en"

theme_skin: "default"
minimal_mistakes_skin: "default"
title_separator: "—"

author:
  name: "Mingze Li"
  avatar: "/assets/images/20250722035914.jpg"
  bio: "M.Sc. Information Systems · KIT"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Mingze101"

    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:mesenlee@163.com"

    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/mingze-li-987147363/"

markdown: kramdown

kramdown:
  input: GFM
  parse_block_html: true
  parse_span_html: true

highlighter: rouge

plugins:
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
